version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    volumes:
      - ./backend:/app
      - gem_cache:/usr/local/bundle
      - sqlite_data:/app/db
    command: bundle exec rails s -b 0.0.0.0

volumes:
  gem_cache:
  sqlite_data: 