source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.4'

# Rails 7.1以降を指定
gem 'rails', '~> 7.1.3'
# SQLite3をデータベースとして使用
gem 'sqlite3', '~> 1.6'
# Pumaをアプリケーションサーバーとして使用
gem 'puma', '~> 6.0'
# CORSハンドリング用
gem 'rack-cors'
# 起動時間高速化
gem 'bootsnap', require: false

group :development, :test do
  # デバッグ用
  gem 'debug', platforms: [:mri, :mingw, :x64_mingw]
  # テスト用
  gem 'rspec-rails', '~> 6.0.0'
end

group :development do
  # ファイル変更監視
  gem 'listen', '~> 3.3'
end

# Windowsプラットフォーム用
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby] 