name: Branch Protection

on:
  pull_request:
    branches:
      - develop
      - production

jobs:
  check_branch_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch for protection rules
        id: branch-check
        run: |
          # ブランチ情報の取得
          SOURCE_BRANCH="${{ github.head_ref }}"
          TARGET_BRANCH="${{ github.base_ref }}"
          
          echo "Source branch: $SOURCE_BRANCH"
          echo "Target branch: $TARGET_BRANCH"
          
          # developブランチへのPRはfeature/*ブランチからのみ許可
          if [ "$TARGET_BRANCH" == "develop" ] && [[ ! "$SOURCE_BRANCH" =~ ^feature/.+ ]]; then
            echo "Error: Pull requests to develop branch must come from a feature branch (feature/*)."
            exit 1
          fi
          
          # productionブランチへのPRはdevelopブランチからのみ許可
          if [ "$TARGET_BRANCH" == "production" ] && [ "$SOURCE_BRANCH" != "develop" ]; then
            echo "Error: Pull requests to production branch must come from the develop branch."
            exit 1
          fi
          
          echo "Branch protection rules passed." 